### ISSUE TITLE
Cut release to address Node.js 16 deprecation warnings

### ISSUE THREAD

**Issue by NotMyFault** [helm/kind-action#103]
Hey @davidkarlsen,

I see that you approved and merged https://github.com/helm/kind-action/pull/102 addressing the Node.js 16 warning in GH actions:
![Screenshot 2024-02-11 at 12 45 13](https://github.com/helm/kind-action/assets/13383509/a5bf824d-1475-4bec-82e1-6e49719a0ffd)

Would you mind cutting a release including this change, please? That would address the deprecation warning when updating the action.

Thanks in advance!

**Comment by davidkarlsen** [comment]
Fixed in `v1.9.0`

**Comment by NotMyFault** [comment]
> Fixed in `v1.9.0`

Thanks a lot!
