### ISSUE TITLE
Is it possible to access a GitHub action service inside the kind?

### ISSUE THREAD

**Issue by paulobressan** [helm/kind-action#118]
I have a Kafka service configured and two Kinds running, so one Kind will be running a producer client and the other a consumer. The consumer will create native resources in the cluster.

But, how can I access the Kafka service configured in github action from inside of the pod? Is it possible?

That's the error that I'm getting
```
Error: No host reachable
```

The Kafka host was set like this `localhost:9092`

**Comment by dineshba** [comment]
Is your Kafka running in github action runner in some port ? Inside the kind cluster (and in the pod), localhost will have different meaning.

I am not sure if you have tried this. Can we get the github action runner IP and use that IP directly instead of localhost ?

**Comment by paulobressan** [comment]
Hi @dineshba thank you for your answer, I changed to use everything inside the kind cluster using only one cluster

**Comment by dineshba** [comment]
Shall we close this if it is not relevant any more?
