### ISSUE TITLE
Request for a new v1.11.0 release

### ISSUE THREAD

**Issue by astefanutti** [helm/kind-action#128]
May I kindly ask for cutting a new v1.11.0 release that would include #127.

Starting Kubernetes v1.30, the kubectl binaries are only hosted on `dl.k8s.io` so it's only possible to use this action with #127.

Thanks!

**Comment by cpanato** [comment]
waiting this to be merged https://github.com/helm/kind-action/pull/122

**Comment by cpanato** [comment]
done here https://github.com/helm/kind-action/releases/tag/v1.11.0

**Comment by astefanutti** [comment]
Thanks a lot for the release!

**Comment by EmilTholin** [comment]
Thank you so much for this release.

Is https://github.com/helm/kind-action/pull/113 up for thorough testing in `main` first, or it that about to be released as well?
