### ISSUE TITLE
syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by zhuwenxing** [helm/kind-action#48]
In my Github action, sometimes using kind-action will have problem installing cluster fail

The error logs are:
```
Run helm/kind-action@v1.2.0
  with:
/opt/hostedtoolcache/kind/v0.11.1/x86_64/kind/bin//kind: line 1: syntax error near unexpected token `newline'
/opt/hostedtoolcache/kind/v0.11.1/x86_64/kind/bin//kind: line 1: `<?xml version="1.0" encoding="UTF-8"?>'
Installing kind...
Adding kind directory to PATH...
Installing kubectl...
Adding kubectl directory to PATH...
```

**Comment by cpanato** [comment]
this seems to be some gh issue, closing for now.
if you still face this issue, please reopen or open a new issue and add some links for existing runs

thanks!

**Comment by barnabasbusa** [comment]
is there any open issue regarding this? I also have the same issue, and its quite frustrating that sometimes I have to manually trigger a rerun for a specific action and then it passes without any issues. 
Or is there any workaround possibly?
