### ISSUE TITLE
post-action clean up job occasional failed on self-hosted github action runners

### ISSUE THREAD

**Issue by jerry153fish** [helm/kind-action#54]
I have seen the cleanup jobs fails on our ci for multiple times in our self-hosted github runners 

```
ERROR: failed to delete cluster "local": failed to delete nodes: command "docker rm -f -v local-control-plane" failed with error: exit status 1

Command Output: Error response from daemon: Could not kill running container 25a65[4] xxxx cannot remove - tried to kill container, but did not receive an exit event
```

This might be caused by https://github.com/kubernetes-sigs/kind/issues/708. 

Is it possible to add an option input `failed_on_cleanup` to force `kind delete` to return ture eg:

```
   kind delete xxx || true # if failed_on_cleanup set to false
```

**Comment by bianchi2** [comment]
I see the same issue, though in my case it's related to types of workloads deployed to the cluster. To mitigate it I delete workloads and restart docker too.

**Comment by Chinwendu20** [comment]
Yeah I am having the same issue
