### ISSUE TITLE
How to mount host directory to kind pod in GA?

### ISSUE THREAD

**Issue by dcoliversun** [helm/kind-action#67]
Hi team. In minikube, I can use `minikube mount <source directory>:<target directory>` to complete it. What's steps in kind-action? Shall we need input parameter to support?  
Any help will be appreciated.

**Comment by markercm** [comment]
In Kind you can use the [`extraMounts`](https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts) option to do this.  It is easier to do if you are using a configuration file like the linked example.

**Comment by dcoliversun** [comment]
Thanks @markercm It works :)
