### ISSUE TITLE
Question: Support for PersistentVolumeClaims?

### ISSUE THREAD

**Issue by Hyperclaw79** [helm/kind-action#94]
Does kind-action support (and Github allows) PersistentVolumeClaims while running K8s inside a Github Action? I have seen an Insufficient CPU error while testing a RabbitMQ StatefulSet and it made me wonder if the resource limits are the issue or whether it is even possible to create persistent volumes during the lifecycle of GA.

**Comment by davidkarlsen** [comment]
It should work fine. See https://mauilion.dev/posts/kind-pvc/

**Comment by Hyperclaw79** [comment]
Thank you for the confirmation and the reference link. Closing the issue for now.
